export { default as FilterSelectLeague } from '../../components/Filter/SelectLeague.vue'
export { default as FilterSelectLeagueMpy } from '../../components/Filter/SelectLeagueMpy.vue'
export { default as LayoutsAds } from '../../components/layouts/Ads.vue'
export { default as LayoutsAnnouncementIframe } from '../../components/layouts/Announcement-Iframe.vue'
export { default as LayoutsAnnouncement } from '../../components/layouts/Announcement.vue'
export { default as LayoutsCenter } from '../../components/layouts/Center.vue'
export { default as LayoutsFooter } from '../../components/layouts/Footer.vue'
export { default as LayoutsHeader } from '../../components/layouts/Header.vue'
export { default as LayoutsLoadingBar } from '../../components/layouts/LoadingBar.vue'
export { default as LayoutsMenuCenter } from '../../components/layouts/MenuCenter.vue'
export { default as LayoutsOptionMenu } from '../../components/layouts/OptionMenu.vue'
export { default as LayoutsSidebarLeft } from '../../components/layouts/SidebarLeft.vue'
export { default as LayoutsSidebarRight } from '../../components/layouts/SidebarRight.vue'
export { default as HeaderLogo } from '../../components/header/Logo.vue'
export { default as HeaderMenuLeft } from '../../components/header/MenuLeft.vue'
export { default as HeaderMenuRight } from '../../components/header/MenuRight.vue'
export { default as HeaderOptionMenu } from '../../components/header/OptionMenu.vue'
export { default as HeaderOptionMenuIframe } from '../../components/header/OptionMenuIframe.vue'
export { default as HeaderSelectOption } from '../../components/header/SelectOption.vue'
export { default as HeaderUserCredit } from '../../components/header/UserCredit.vue'
export { default as HeaderRules } from '../../components/header/rules.vue'
export { default as Center2Basketball } from '../../components/center2/Basketball.vue'
export { default as Center2Bullfight } from '../../components/center2/Bullfight.vue'
export { default as Center2Cockfight } from '../../components/center2/Cockfight.vue'
export { default as Center2Cockfightsouth } from '../../components/center2/Cockfightsouth.vue'
export { default as Center2Football } from '../../components/center2/Football.vue'
export { default as Center2Football2 } from '../../components/center2/Football2.vue'
export { default as Center2Iframebox } from '../../components/center2/Iframebox.vue'
export { default as Center2Muaythai } from '../../components/center2/Muaythai.vue'
export { default as Center2SelectLeagueButton } from '../../components/center2/SelectLeagueButton.vue'
export { default as Center2Snooker } from '../../components/center2/Snooker.vue'
export { default as Center2Takraw } from '../../components/center2/Takraw.vue'
export { default as Center2Title } from '../../components/center2/Title.vue'
export { default as NumberFormatNumber } from '../../components/number/FormatNumber.vue'
export { default as SidebarLeftBanner } from '../../components/sidebar-left/Banner.vue'
export { default as SidebarLeftBetList } from '../../components/sidebar-left/BetList.vue'
export { default as SidebarLeftBetinfoBetType } from '../../components/sidebar-left/BetinfoBetType.vue'
export { default as SidebarLeftBetinfoMenu } from '../../components/sidebar-left/BetinfoMenu.vue'
export { default as SidebarLeftCreditInformation } from '../../components/sidebar-left/CreditInformation.vue'
export { default as SidebarLeftFavorite } from '../../components/sidebar-left/Favorite.vue'
export { default as SidebarLeftListMenu } from '../../components/sidebar-left/ListMenu.vue'
export { default as SidebarLeftSportBetParlay } from '../../components/sidebar-left/SportBetParlay.vue'
export { default as SidebarLeftSportBetSingle } from '../../components/sidebar-left/SportBetSingle.vue'
export { default as SidebarLeftSportMenuItem } from '../../components/sidebar-left/SportMenuItem.vue'
export { default as CenterBasketball } from '../../components/center/Basketball.vue'
export { default as CenterBullfight } from '../../components/center/Bullfight.vue'
export { default as CenterCockfight } from '../../components/center/Cockfight.vue'
export { default as CenterFootball } from '../../components/center/Football.vue'
export { default as CenterMuaythai } from '../../components/center/Muaythai.vue'
export { default as CenterRefreshButton } from '../../components/center/RefreshButton.vue'
export { default as CenterSelectLeagueButton } from '../../components/center/SelectLeagueButton.vue'
export { default as CenterSnooker } from '../../components/center/Snooker.vue'
export { default as CenterTitle } from '../../components/center/Title.vue'
export { default as SidebarRightBanner } from '../../components/sidebar-right/Banner.vue'
export { default as SidebarRightLastBet } from '../../components/sidebar-right/LastBet.vue'
export { default as SidebarRightLastBetText } from '../../components/sidebar-right/LastBetText.vue'
export { default as TvIframe } from '../../components/tv/iframe.vue'
export { default as UserAccount } from '../../components/user/Account.vue'
export { default as UserBalance } from '../../components/user/Balance.vue'
export { default as UserMyBet } from '../../components/user/MyBet.vue'
export { default as UserStatement } from '../../components/user/Statement.vue'
export { default as UserTabs } from '../../components/user/Tabs.vue'
export { default as Center2ColumnHandicap } from '../../components/center2/column/Handicap.vue'
export { default as Center2ColumnName } from '../../components/center2/column/Name.vue'
export { default as Center2ColumnPoint } from '../../components/center2/column/Point.vue'
export { default as Center2ColumnPrice } from '../../components/center2/column/Price.vue'
export { default as Center2ColumnScore } from '../../components/center2/column/Score.vue'
export { default as Center2ColumnTime } from '../../components/center2/column/Time.vue'
export { default as Center2ColumnTime2 } from '../../components/center2/column/Time2.vue'
export { default as Center2ColumnTimeMuay } from '../../components/center2/column/TimeMuay.vue'
export { default as Center2Column2Point } from '../../components/center2/column2/Point.vue'
export { default as Center2Column2Point2 } from '../../components/center2/column2/Point2.vue'
export { default as Center2Column2Price } from '../../components/center2/column2/Price.vue'
export { default as Center2Column2PriceDouble } from '../../components/center2/column2/PriceDouble.vue'
export { default as Center2Column2Time } from '../../components/center2/column2/Time.vue'
export { default as Center2Column2Price2 } from '../../components/center2/column2/price2.vue'
export { default as Center2MatchTableEarly } from '../../components/center2/match-table/Early.vue'
export { default as Center2MatchTableEarlyMpy } from '../../components/center2/match-table/EarlyMpy.vue'
export { default as Center2MatchTableLive } from '../../components/center2/match-table/Live.vue'
export { default as Center2MatchTableLive2 } from '../../components/center2/match-table/Live2.vue'
export { default as Center2MatchTableLiveMpy } from '../../components/center2/match-table/LiveMpy.vue'
export { default as Center2MatchTableNonlive } from '../../components/center2/match-table/Nonlive.vue'
export { default as Center2MatchTableNonliveMpy } from '../../components/center2/match-table/NonliveMpy.vue'
export { default as MenubarAnnounceTable } from '../../components/menubar/announce/Table.vue'
export { default as MenubarResultsFilterResult } from '../../components/menubar/results/FilterResult.vue'
export { default as MenubarResultsFilterSelectLeague } from '../../components/menubar/results/FilterSelectLeague.vue'
export { default as MenubarResultsTable } from '../../components/menubar/results/Table.vue'
export { default as MenubarResults2FilterResult } from '../../components/menubar/results2/FilterResult.vue'
export { default as MenubarResults2FilterSelectLeague } from '../../components/menubar/results2/FilterSelectLeague.vue'
export { default as MenubarResults2Table } from '../../components/menubar/results2/Table.vue'
export { default as CenterMatchTableDoubleLine } from '../../components/center/match-table/DoubleLine.vue'
export { default as CenterMatchTableFulltimeOnly } from '../../components/center/match-table/FulltimeOnly.vue'
export { default as CenterMatchTableHalftimeOnly } from '../../components/center/match-table/HalftimeOnly.vue'
export { default as CenterMatchTableLive } from '../../components/center/match-table/Live.vue'
export { default as CenterMatchTableSingleLine } from '../../components/center/match-table/SingleLine.vue'
export { default as CenterMatchTableTdmpyzoo } from '../../components/center/match-table/Tdmpyzoo.vue'
export { default as CenterMatchTableToday } from '../../components/center/match-table/Today.vue'
export { default as Center2MatchTableDoubleTables } from '../../components/center2/match-table/double/Tables.vue'
export { default as Center2MatchTableHalftimeTables } from '../../components/center2/match-table/halftime/Tables.vue'
export { default as Center2MatchTableFulltimeTables } from '../../components/center2/match-table/fulltime/Tables.vue'
export { default as Center2MatchTableFulltimeTablesMuay } from '../../components/center2/match-table/fulltime/TablesMuay.vue'
export { default as Center2MatchTableFulltimeTablesMuay2 } from '../../components/center2/match-table/fulltime/TablesMuay2.vue'
export { default as Center2MatchTableNewlineTables } from '../../components/center2/match-table/newline/Tables.vue'
export { default as Center2MatchTableNewlineThDouble } from '../../components/center2/match-table/newline/ThDouble.vue'
export { default as Center2MatchTableNewlineThSingle } from '../../components/center2/match-table/newline/ThSingle.vue'
export { default as Center2MatchTableSingleTables } from '../../components/center2/match-table/single/Tables.vue'
export { default as Center2MatchTable2DoubleEarly } from '../../components/center2/match-table2/double/Early.vue'
export { default as Center2MatchTable2DoubleLive } from '../../components/center2/match-table2/double/Live.vue'
export { default as Center2MatchTable2DoubleNonlive } from '../../components/center2/match-table2/double/Nonlive.vue'
export { default as Center2MatchTable2Double } from '../../components/center2/match-table2/double/index.vue'
export { default as Center2MatchTable2FulltimeEarly } from '../../components/center2/match-table2/fulltime/Early.vue'
export { default as Center2MatchTable2FulltimeLive } from '../../components/center2/match-table2/fulltime/Live.vue'
export { default as Center2MatchTable2FulltimeNonlive } from '../../components/center2/match-table2/fulltime/Nonlive.vue'
export { default as Center2MatchTable2FulltimeTables } from '../../components/center2/match-table2/fulltime/Tables.vue'
export { default as Center2MatchTable2FulltimeTablesMuay } from '../../components/center2/match-table2/fulltime/TablesMuay.vue'
export { default as Center2MatchTable2Fulltime } from '../../components/center2/match-table2/fulltime/index.vue'
export { default as Center2MatchTable2HalftimeEarly } from '../../components/center2/match-table2/halftime/Early.vue'
export { default as Center2MatchTable2HalftimeLive } from '../../components/center2/match-table2/halftime/Live.vue'
export { default as Center2MatchTable2HalftimeNonlive } from '../../components/center2/match-table2/halftime/Nonlive.vue'
export { default as Center2MatchTable2HalftimeTables } from '../../components/center2/match-table2/halftime/Tables.vue'
export { default as Center2MatchTable2HalftimeHeadtable } from '../../components/center2/match-table2/halftime/headtable.vue'
export { default as Center2MatchTable2Halftime } from '../../components/center2/match-table2/halftime/index.vue'
export { default as Center2MatchTable2Headtable } from '../../components/center2/match-table2/headtable/index.vue'
export { default as Center2MatchTable2NewlineTables } from '../../components/center2/match-table2/newline/Tables.vue'
export { default as Center2MatchTable2NewlineThDouble } from '../../components/center2/match-table2/newline/ThDouble.vue'
export { default as Center2MatchTable2NewlineThSingle } from '../../components/center2/match-table2/newline/ThSingle.vue'
export { default as Center2MatchTable2SinglelineEarly } from '../../components/center2/match-table2/singleline/Early.vue'
export { default as Center2MatchTable2SinglelineLive } from '../../components/center2/match-table2/singleline/Live.vue'
export { default as Center2MatchTable2SinglelineNonlive } from '../../components/center2/match-table2/singleline/Nonlive.vue'
export { default as Center2MatchTable2Singleline } from '../../components/center2/match-table2/singleline/index.vue'
export { default as CenterMatchTableDoubleTdfootball } from '../../components/center/match-table/double/Tdfootball.vue'
export { default as CenterMatchTableFulltimeTdfootball } from '../../components/center/match-table/fulltime/Tdfootball.vue'
export { default as CenterMatchTableColumnName } from '../../components/center/match-table/column/Name.vue'
export { default as CenterMatchTableColumnPrice } from '../../components/center/match-table/column/Price.vue'
export { default as CenterMatchTableColumnScore } from '../../components/center/match-table/column/Score.vue'
export { default as CenterMatchTableColumnTime } from '../../components/center/match-table/column/Time.vue'
export { default as CenterMatchTableSingleTdfootball } from '../../components/center/match-table/single/Tdfootball.vue'
export { default as CenterMatchTableHalftimeTdfootball } from '../../components/center/match-table/halftime/Tdfootball.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
